### ISSUE TITLE
Create Clickable Button for 'X'

### ISSUE THREAD

**Issue by o-david** [o-david/tic-tac-toe#1]

**Comment by o-david** [comment]
For this issue, it's basically creating a clickable button to represent moves right?

**Comment by Chizaram-Igolo** [comment]
Yes, this is correct.

**Comment by gabbyedgar** [comment]
I think if you're taking this, you can also handle the next issue ( build the board layout)

**Comment by o-david** [comment]
Alight

**Comment by o-david** [comment]
Thanks for merging @Chizaram-Igolo
