### ISSUE TITLE
Add Event Handler for Going To Previous Moves

### ISSUE THREAD

**Issue by Chizaram-Igolo** [o-david/tic-tac-toe#11]

**Comment by Chizaram-Igolo** [comment]
I'll take up this issue.

**Comment by Chizaram-Igolo** [comment]
Done. Please, check that the feature works correctly.

**Comment by o-david** [comment]
I have checked but it's up to date with the main branch
<img width="994" alt="Screenshot 2023-08-17 at 16 07 34" src="https://github.com/o-david/tic-tac-toe/assets/30634148/6d552ce2-9e8c-4c41-965c-e8c0c12b603a">
please check that your update was uploaded successfully

**Comment by Chizaram-Igolo** [comment]
> I have checked but it's up to date with the main branch <img alt="Screenshot 2023-08-17 at 16 07 34" width="994" src="https://user-images.githubusercontent.com/30634148/261352818-6d552ce2-9e8c-4c41-965c-e8c0c12b603a.png"> please check that your update was uploaded successfully 

Thank you for pointing that out. I have pushed the changes now. 😅
