### ISSUE TITLE
Add Styles for Better Presentation

### ISSUE THREAD

**Issue by Chizaram-Igolo** [o-david/tic-tac-toe#12]
Fix default `height` of buttons when empty.

**Comment by Chizaram-Igolo** [comment]
I will be applying some CSS styles to improve the presentation of the Tic-Tac-Toe game. I will also fix the height of the buttons.

**Comment by o-david** [comment]
Sure, please let us know when you are done

**Comment by Chizaram-Igolo** [comment]
Done. Please, review and merge.

**Comment by o-david** [comment]
Reviewing...

**Comment by o-david** [comment]
You have a couple of commented codes in the CSS file, please check it out

**Comment by o-david** [comment]
Line 93-105

**Comment by Chizaram-Igolo** [comment]
> Line 93-105

Alternate styles. I will get rid of those lines in the next commit.

**Comment by o-david** [comment]
So I should merge anyways?

**Comment by Chizaram-Igolo** [comment]
> So I should merge anyways?

Yes.
