### ISSUE TITLE
Pass Data Through Props

### ISSUE THREAD

**Issue by o-david** [o-david/tic-tac-toe#3]

**Comment by gabbyedgar** [comment]
alright I'll work on this task

**Comment by gabbyedgar** [comment]
Done with this task. Please somebody check it out

**Comment by Chizaram-Igolo** [comment]
> Done with this task. Please somebody check it out

Will check it out now.

**Comment by Chizaram-Igolo** [comment]
Seen. All good! 👍

**Comment by o-david** [comment]
I think it's fine

**Comment by gabbyedgar** [comment]
Alright 🥂
