### ISSUE TITLE
Add Event Handler For Clicking Buttons

### ISSUE THREAD

**Issue by o-david** [o-david/tic-tac-toe#4]

**Comment by gabbyedgar** [comment]
Can I take up this task? 😁

**Comment by o-david** [comment]
> Can I take up this task? 😁

@Chizaram-Igolo already moved it to in progress, I think he is working on it

**Comment by Chizaram-Igolo** [comment]
> > Can I take up this task? 😁
> 
> @Chizaram-Igolo already moved it to in progress, I think he is working on it

Yes, @o-david is right. I am working on it already. I'm almost done.

**Comment by Chizaram-Igolo** [comment]
Issue addressed. Please confirm that this feature works correctly. 😃

**Comment by gabbyedgar** [comment]
Checking it out!

**Comment by o-david** [comment]
I noticed the the default height of the buttons are shorter when empty

**Comment by gabbyedgar** [comment]
Yeah i noticed that too. We can add that to the last issue but let me proceed to merge the branches😄

**Comment by o-david** [comment]
> Yeah i noticed that too. We can add that to the last issue but let me proceed to merge the branches😄

Cool

**Comment by Chizaram-Igolo** [comment]
> Yeah i noticed that too. We can add that to the last issue but let me proceed to merge the branches😄

I've added that to the last issue. Thanks for pointing that out.
