### ISSUE TITLE
Add State for Setting Turns

### ISSUE THREAD

**Issue by Chizaram-Igolo** [o-david/tic-tac-toe#7]

**Comment by o-david** [comment]
Hi team, I am working on this issue

**Comment by gabbyedgar** [comment]
Go on!

**Comment by Chizaram-Igolo** [comment]
> Hi team, I am working on this issue

Great. 👍

**Comment by o-david** [comment]
All done with this issue, please vet

**Comment by Chizaram-Igolo** [comment]
> All done with this issue

I'll have a look.

**Comment by Chizaram-Igolo** [comment]
All good! Merged!
