### ISSUE TITLE
Add Array of Possible Win Positions

### ISSUE THREAD

**Issue by Chizaram-Igolo** [o-david/tic-tac-toe#8]

**Comment by o-david** [comment]
Just to confirm the possible wins are vertically and horizontally right? 
Vertically
0, 1, 2
3, 4, 5
6, 7, 8
Horizontally 
0, 3, 6
1, 4, 7
2, 5, 8

**Comment by Chizaram-Igolo** [comment]
> Just to confirm the possible wins are vertically and horizontally right? Vertically 0, 1, 2 3, 4, 5 6, 7, 8 Horizontally 0, 3, 6 1, 4, 7 2, 5, 8

Yes. In addition, you can have diagonal win positions like: 

0, 4, 8, and
2, 4, 6

**Comment by o-david** [comment]
I have added an array of all the possible win positions we agreed on here please check and merge

**Comment by Chizaram-Igolo** [comment]
> I have added an array of all the possible win positions we agreed on here please check and merge

Will do that now. 👍

**Comment by Chizaram-Igolo** [comment]
> I have added an array of all the possible win positions we agreed on here please check and merge. 

Done. I've merged your changes. Well done.
